name: Calance generic CI-CD
on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+
    branches:
    - 'main'
    paths:
    - 'Dockerfile'
    - '**.py'
  workflow_dispatch:


jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository (clone the repo for use)
      uses: actions/checkout@v3

    - name: Log in to github Container registry where image is pushed and pulled from
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ secrets.REPOSITORY_OWNER }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        #image name should ideally be ghcr.io/${{ secrets.REPOSITORY_OWNER }}/${{ inputs.image_name }}
        #but it throws error while pulling image with this. it is building the image but not able to push in github container registry
        images: |
          ghcr.io/${{ github.repository_owner }}/build-jenkins-job-image
        tags: |
          type=semver,pattern={{version}}


    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: "./Dockerfile"

