name: Calance generic CI-CD
on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:


jobs:
  build-and-push-dockerimages:
    secrets:
      IMAGE_REGISTRY_PASSWORD : ${{ secrets.GHCR_TOKEN }}
    uses: Calance-US/calance-workflows/.github/workflows/build.yml@v3.0.1
    with:
      image_name: Calance-US/build-jenkins-job
      image_registry: ghcr.io
      image_registry_username: Calance-US
      


